### ISSUE TITLE
Consider creating separate callbacks for some notifications

### ISSUE THREAD

**Issue by mspanc** [membraneframework/membrane-core#123]
Currently, for example, the pipeline is receiving a notification `{:start_of_stream, :input}` when the stream starts.

Originally the messages, now called notifications were created to create the way of capturing messages *from the elements*. They're by design highly customizable by an ability to pass an arbitrary structure to a notification, as we're not able to predict all possible elements and their use cases.

The Core's callbacks are kind of reverse are well defined and do not change depending on the actual element being used.

IMO we should add new callbacks such as `handle_start_of_stream` for all cases of notifications currently issued by non-elements.

**Comment by mat-hek** [comment]
I'm not sure about this. Actually, messages such as `:start_of_stream` are also sent from elements. Usually, it's done by the default implementation of `handle_event`, but there are situations where this behaviour should be overridden. Consider `:end_of_stream` - when the sink receives the end of stream event, it may have some data enqueued in its internal buffers, and the actual end of stream happens when it consumes all such data. That's when a notification to the pipeline should be sent. Anyway, we can differentiate such 'well-known' messages from the others, but I'm not sure it's worth adding and maintaining more callbacks. Maybe we could just mark them for easier matching, e.g. `{:lifecycle, start_of_stream: :input}`, `{:lifecycle, end_of_stream: :input}`.

**Comment by mspanc** [comment]
The example of a notification is an audio level emitted by the audiometer element every 100ms even if there's no data flowing through it. This notification is not aligned with the buffers.

Another example might be a notification with the transcription received asynchronously from the API in the ibm_text_too_speech element - we cannot predict when we will receive the data from the API and we emit it as soon as it arrives. 

EOS and similar events are tightly aligned with the buffers flowing through an element.

Thus, these are two distinct concepts.

Moreover, EOS and similar events are universal concepts that apply to many elements but each element can have its very unique set of notifications that are closely related to the purpose of the element. 

Once that is implemented we have to remind to remove such things:

https://github.com/membraneframework/membrane-core/pull/152/files#diff-5ef6210a9e3216dd9b86d957ec4714f4R9

Given that I will strongly advocate for creating more `handle_*` callbacks for EOS and similar events.

**Comment by bblaszkow06** [comment]
Done in #174
