### ISSUE TITLE
Add equivalent of GenServer's terminate callback

### ISSUE THREAD

**Issue by mspanc** [membraneframework/membrane-core#129]
We should have equivalent of GenServer's terminate (e.g. handle_terminate) both in pipelines and elements to allow proper cleanup.

**Comment by mat-hek** [comment]
We already have this in elements, ([handle_shutdown/1](https://hexdocs.pm/membrane_core/Membrane.Element.Base.Mixin.CommonBehaviour.html#c:handle_shutdown/1)), we should only add Pipeline's counterpart. BTW I'm not sure if it should be the only solution anyway, because GenServer's terminate callback is not guaranteed to be executed (see https://hexdocs.pm/elixir/GenServer.html#c:terminate/2. So we should either spawn a process for monitoring each element/pipeline and execute such callbacks there or encourage users to create such processes for each resource that needs to be cleaned up (the way the File does it)

**Comment by bblaszkow06** [comment]
`handle_shutdown` for pipelines done in #176
